export const hoaxData = [
  {
    id: 1,
    title: "[HOAKS] Akun WhatsApp dan Facebook Mengatasnamakan Sekretaris Dinas Pendidikan dan Kebudayaan Kabupaten Magelang Amirudin Zuhri",
    topic: "pejabat",
    status: "hoax",
    date: "2026-03-31",
    source: "Kementerian Komunikasi dan Digital",
    sourceUrl: "https://www.komdigi.go.id/berita/berita-hoaks/detail/hoaks-akun-whatsapp-dan-facebook-mengatasnamakan-sekretaris-dinas-pendidikan-dan-kebudayaan-kabupaten-magelang-amirudin-zuhri",
    excerpt: "Akun WhatsApp (+62 851-2497-5576) menggunakan nama dan foto profil Sekretaris Dinas Pendidikan Magelang untuk menghubungi masyarakat.",
    fullContent: "Faktanya, akun WhatsApp tersebut adalah tidak benar. Dilansir dari akun Instagram Diskominfo Kabupaten Magelang @kominfomagelang, nomor WhatsApp tersebut bukan milik Sekretaris Dinas Pendidikan dan Kebudayaan Amirudin Zuhri. Masyarakat diimbau untuk tidak menanggapi dan tidak memberikan data pribadi atau bantuan dana."
  },
  {
    id: 2,
    title: "[HOAKS] Presiden Prabowo Umumkan PPPK Paruh Waktu Mulai Beralih ke PNS",
    topic: "kebijakan",
    status: "hoax",
    date: "2026-03-31",
    source: "Kementerian Komunikasi dan Digital",
    sourceUrl: "https://www.komdigi.go.id/berita/berita-hoaks/detail/hoaks-presiden-prabowo-umumkan-pppk-paruh-waktu-mulai-beralih-ke-pns",
    excerpt: "Unggahan di Facebook mengeklaim Presiden Prabowo menyampaikan pernyataan resmi terkait rencana pengangkatan PPPK paruh waktu langsung menjadi PNS.",
    fullContent: "Faktanya, klaim tersebut adalah hoaks. Dilansir dari tirto.id, tidak ditemukan informasi dari media kredibel yang membenarkan klaim Presiden Prabowo mengumumkan peralihan status tersebut secara otomatis. Sampai saat ini kebijakan tersebut masih dalam tahap pembahasan regulasi teknis."
  },
  {
    id: 3,
    title: "[HOAKS] AS Terjunkan 10.000 Prajurit Robot untuk Serang Iran",
    topic: "umum",
    status: "hoax",
    date: "2026-03-31",
    source: "Kementerian Komunikasi dan Digital",
    sourceUrl: "https://www.komdigi.go.id/berita/berita-hoaks/detail/hoaks-as-terjunkan-10000-prajurit-robot-untuk-serang-iran",
    excerpt: "Amerika Serikat (AS) dikabarkan telah mengirimkan 10.000 prajurit robot untuk melakukan serangan terhadap Iran.",
    fullContent: "Faktanya, klaim tersebut tidak benar. Hasil pengecekan menggunakan Hive Moderation dan Bitmind menunjukkan video tersebut 99,9% merupakan hasil AI (Artificial Intelligence). Tidak ada laporan resmi mengenai pengerahan robot tempur massal ke wilayah tersebut."
  },
  {
    id: 4,
    title: "[HOAKS] Presiden Prabowo Tunjuk Susi Pudjiastuti, Mahfud MD, dan Ahok jadi Pimpinan KPK",
    topic: "pejabat",
    status: "hoax",
    date: "2026-03-31",
    source: "Kementerian Komunikasi dan Digital",
    sourceUrl: "https://www.komdigi.go.id/berita/berita-hoaks/detail/hoaks-presiden-prabowo-tunjuk-susi-pudjiastuti-mahfud-md-dan-ahok-jadi-pimpinan-kpk",
    excerpt: "Video mengeklaim Presiden Prabowo resmi melantik Susi Pudjiastuti, Mahfud MD, dan Ahok sebagai pimpinan baru KPK.",
    fullContent: "Faktanya, klaim tersebut telah dibantah oleh berbagai sumber kredibel termasuk Antara News dan Tempo. Pimpinan KPK saat ini masih diketuai oleh Setyo Budiyanto berdasarkan hasil seleksi resmi, dan tokoh-tokoh yang disebutkan tidak masuk dalam struktur pimpinan saat ini."
  },
  {
    id: 5,
    title: "[HOAKS] Akun TikTok Mengatasnamakan KBRI Kuala Lumpur",
    topic: "umum",
    status: "hoax",
    date: "2026-03-31",
    source: "Kementerian Komunikasi dan Digital",
    sourceUrl: "https://www.komdigi.go.id/berita/berita-hoaks/detail/hoaks-akun-tiktok-mengatasnamakan-kbri-kuala-lumpur",
    excerpt: "Beredar akun TikTok yang menggunakan logo Pancasila dan nama Kedutaan Besar Republik Indonesia Kuala Lumpur untuk pelayanan WNI.",
    fullContent: "Faktanya, KBRI Kuala Lumpur menegaskan melalui Instagram resminya @indonesiainkualalumpur bahwa mereka tidak memiliki akun TikTok resmi. Akun tersebut adalah akun palsu yang berpotensi melakukan penipuan data pribadi."
  },
  {
    id: 6,
    title: "[HOAKS] Presiden Prabowo Dibuatkan Lagu Oleh Musisi Dunia karena Terlibat di Board of Peace",
    topic: "umum",
    status: "hoax",
    date: "2026-03-31",
    source: "Kementerian Komunikasi dan Digital",
    sourceUrl: "https://www.komdigi.go.id/berita/berita-hoaks/detail/hoaks-presiden-prabowo-dibuatkan-lagu-oleh-musisi-dunia-karena-terlibat-di-board-of-peace",
    excerpt: "Video musik mengeklaim musisi internasional menciptakan lagu khusus untuk Prabowo atas perannya di Board of Peace (BoP).",
    fullContent: "Faktanya, lagu tersebut adalah hasil buatan AI. Pengecekan Hive Moderation menunjukkan indikasi AI sebesar 96,7%. Kanal asli pengunggah video tersebut juga menyertakan label bahwa konten merupakan hasil modifikasi sintetis."
  },
  {
    id: 7,
    title: "[HOAKS] FIFA Tunjuk Indonesia Jadi Tuan Rumah Piala Dunia 2026 Gantikan Meksiko",
    topic: "umum",
    status: "hoax",
    date: "2026-03-31",
    source: "Kementerian Komunikasi dan Digital",
    sourceUrl: "https://www.komdigi.go.id/berita/berita-hoaks/detail/hoaks-fifa-tunjuk-indonesia-jadi-tuan-rumah-piala-dunia-2026-gantikan-meksiko",
    excerpt: "FIFA secara mendadak mengalihkan hak tuan rumah Piala Dunia 2026 dari Meksiko ke Indonesia karena masalah keamanan kartel narkoba.",
    fullContent: "Faktanya, tidak ada pengumuman resmi dari FIFA terkait pemindahan ini. Foto yang digunakan dalam klaim adalah foto lama pertemuan Presiden FIFA Gianni Infantino dengan presiden Indonesia sebelumnya pada tahun 2022."
  },
  {
    id: 8,
    title: "[SALAH] Bahlil Dorong PLN Naikkan Harga Token Listrik",
    topic: "kebijakan",
    status: "hoax",
    date: "2026-03-31",
    source: "TurnBackHoax (Mafindo)",
    sourceUrl: "https://turnbackhoax.id/articles/33184-salah-bahlil-dorong-pln-naikkan-harga-token-listrik",
    excerpt: "Narasi mengeklaim Menteri Bahlil memerintahkan PLN menaikkan harga token listrik agar rakyat berhemat.",
    fullContent: "Faktanya, melalui laman resmi pln.co.id per 1 Januari 2026, tarif listrik untuk triwulan pertama tahun 2026 dinyatakan tidak mengalami kenaikan (tetap). Tidak ada pernyataan resmi dari Bahlil terkait instruksi kenaikan tersebut."
  },
  {
    id: 9,
    title: "[SALAH] Mencium Kucing Mampu Sebabkan Infeksi Otak",
    topic: "umum",
    status: "hoax",
    date: "2026-03-31",
    source: "TurnBackHoax (Mafindo)",
    sourceUrl: "https://turnbackhoax.id/articles/33185-salah-mencium-kucing-mampu-sebabkan-infeksi-otak",
    excerpt: "Pesan berantai menyebutkan parasit toksoplasma dari bulu kucing bisa langsung masuk ke otak melalui ciuman.",
    fullContent: "Faktanya, penularan toksoplasmosis terjadi melalui konsumsi feses atau daging yang terkontaminasi, bukan kontak fisik permukaan. Risiko utama toksoplasma adalah pada kesehatan reproduksi, bukan infeksi otak melalui ciuman."
  },
  {
    id: 10,
    title: "[HOAKS] Media Sosial akan Dinonaktifkan Komdigi pada 28 Maret 2026",
    topic: "kebijakan",
    status: "hoax",
    date: "2026-03-28",
    source: "Kementerian Komunikasi dan Digital",
    sourceUrl: "https://www.komdigi.go.id/berita/berita-hoaks/detail/hoaks-media-sosial-akan-dinonaktifkan-komdigi-pada-28-maret-2026",
    excerpt: "Unggahan di TikTok mengeklaim Komdigi akan menonaktifkan seluruh platform media sosial termasuk Facebook, Instagram, TikTok, dan YouTube pada 28 Maret 2026.",
    fullContent: "Faktanya, Komdigi tidak menonaktifkan media sosial. Kebijakan yang berlaku pada 28 Maret 2026 adalah pembatasan usia pengguna berdasarkan Peraturan Menteri Komunikasi dan Digital Nomor 9 Tahun 2026, yang melarang anak di bawah 16 tahun memiliki akun media sosial. Kebijakan ini dikonfirmasi oleh Polri, ANTARA News, dan RRI sebagai hoaks yang sengaja menyesatkan publik."
  },
  {
    id: 11,
    title: "[HOAKS] Harga BBM Resmi Naik pada 9 Maret 2026",
    topic: "ekonomi",
    status: "hoax",
    date: "2026-03-09",
    source: "Kementerian Komunikasi dan Digital",
    sourceUrl: "https://www.komdigi.go.id/berita/berita-hoaks/detail/hoaks-harga-bbm-naik-pada-9-maret-2026",
    excerpt: "Klaim viral di media sosial menyebutkan harga BBM resmi naik serentak pada tanggal 9 Maret 2026.",
    fullContent: "Faktanya, klaim tersebut adalah hoaks. Pertamina secara resmi membantah informasi tersebut dan meminta masyarakat memantau penyesuaian harga hanya melalui situs resmi www.pertamina.com. Juru bicara Kementerian ESDM Dwi Anggia juga menegaskan harga BBM bersubsidi tidak naik menjelang Hari Raya Idul Fitri 1447 H. Tidak ada kebijakan resmi kenaikan BBM pada tanggal yang beredar tersebut."
  },
  {
    id: 12,
    title: "[PENIPUAN] Tautan Pendaftaran Rekrutmen PLN 2026",
    topic: "umum",
    status: "hoax",
    date: "2026-03-03",
    source: "TurnBackHoax (Mafindo)",
    sourceUrl: "https://turnbackhoax.id/articles/32612-penipuan-tautan-pendaftaran-rekrutmen-pln-2026",
    excerpt: "Akun TikTok 'SEPUTAR PLN' mempromosikan rekrutmen PT PLN 2026 dengan klaim pendaftaran dibuka 10 Januari hingga 27 Maret 2026 secara gratis.",
    fullContent: "Faktanya, tidak ada informasi rekrutmen PLN 2026 di portal resmi rekrutmen.pln.co.id. Rekrutmen PLN terakhir tercatat pada November 2025 untuk posisi S1/S2 Hukum. Tautan yang disebarkan mengarah ke halaman tidak resmi yang meminta data pribadi termasuk nama, provinsi asal, dan nomor Telegram — indikasi kuat penipuan phishing pencurian data."
  },
  {
    id: 13,
    title: "[PENIPUAN] Video Bantuan Dana Rp200 Juta–Rp2 Miliar untuk Masyarakat Non-Muslim 2026",
    topic: "umum",
    status: "hoax",
    date: "2026-02-23",
    source: "TurnBackHoax (Mafindo)",
    sourceUrl: "https://turnbackhoax.id/articles/32490-penipuan-bantuan-dana-untuk-masyarakat-non-muslim-2026",
    excerpt: "Video Facebook mengeklaim pemerintah menyalurkan bantuan dana Rp200 juta hingga Rp2 miliar untuk masyarakat non-Muslim dan gereja melalui Kemenag hingga pertengahan 2026.",
    fullContent: "Faktanya, Kementerian Agama secara resmi membantah klaim ini dan menyatakan surat terkait 'penyaluran Bantuan Dana DAP' yang beredar adalah tidak benar. Video tersebut menggunakan footage lama dari liputan banjir di Batang Toru yang dimanipulasi menggunakan teknologi AI untuk menampilkan pembawa berita palsu yang mempromosikan program fiktif."
  },
  {
    id: 19,
    title: "[HOAKS] Link Pendaftaran BLT UMKM Rp5 Juta Batas Akhir 1 April 2026",
    topic: "ekonomi",
    status: "hoax",
    date: "2026-03-31",
    source: "Liputan6 Cek Fakta",
    sourceUrl: "https://www.liputan6.com/cek-fakta/read/6307194/cek-fakta-hoaks-link-pendaftaran-blt-umkm-dengan-batas-akhir-1-april-2026",
    excerpt: "Unggahan Facebook menyebarkan link pendaftaran BLT UMKM senilai Rp5 juta dengan klaim batas akhir pendaftaran 1 April 2026.",
    fullContent: "Faktanya, Kementerian UMKM secara resmi menyatakan: 'Unggahan tersebut tidak benar dan terindikasi penipuan.' Tidak ada program BLT UMKM dari pemerintah saat ini. Modus yang digunakan adalah meminta masyarakat mengisi data pribadi — termasuk nomor Telegram — melalui formulir/link tidak resmi. Informasi resmi hanya tersedia di Instagram @kementerianumkm dan umkm.go.id."
  },
  {
    id: 20,
    title: "[HOAKS] Pertamina Bagikan BBM Gratis di Seluruh SPBU Akhir Maret 2026",
    topic: "ekonomi",
    status: "hoax",
    date: "2026-03-30",
    source: "Liputan6 Cek Fakta",
    sourceUrl: "https://www.liputan6.com/cek-fakta/read/6306219/hoaks-pengisian-bbm-simak-daftarnya-biar-tak-terpengaruh",
    excerpt: "Pesan viral mengeklaim Pertamina mengadakan program pengisian BBM gratis di seluruh SPBU Indonesia pada akhir Maret 2026.",
    fullContent: "Faktanya, PT Pertamina (Persero) secara resmi membantah adanya program pengisian BBM gratis tersebut. Tidak ada pengumuman resmi dari Pertamina terkait program serupa. Hoaks sejenis tentang BBM gratis atau pembatasan pengisian BBM berulang kali beredar dan selalu dibantah oleh Pertamina. Masyarakat diminta memantau informasi hanya melalui kanal resmi pertamina.com."
  },
  {
    id: 21,
    title: "[HOAKS] Pendaftaran Haji Gratis 2026 Dibuka untuk 100 Orang oleh PP APRI",
    topic: "umum",
    status: "hoax",
    date: "2026-03-22",
    source: "Liputan6 Cek Fakta",
    sourceUrl: "https://www.liputan6.com/cek-fakta/read/6305556/deretan-hoaks-seputar-haji-2026-yang-beredar-di-medsos-simak-faktanya",
    excerpt: "Akun Facebook mengeklaim Pengurus Pusat Asosiasi Penghulu Republik Indonesia (PP APRI) membuka pendaftaran haji gratis khusus 100 orang untuk keberangkatan 2027.",
    fullContent: "Faktanya, informasi tersebut adalah palsu. Link yang disertakan mengarah ke formulir yang meminta data pribadi dan nomor Telegram — modus umum penipuan phishing. Tidak ada konfirmasi dari PP APRI maupun Kementerian Agama mengenai program haji gratis dimaksud. Informasi resmi haji hanya tersedia di haji.kemenag.go.id dan kanal resmi Kemenag RI."
  },
  {
    id: 22,
    title: "[HOAKS] Listrik Padam 7 Hari dan Internet Mati Akibat Krisis Global",
    topic: "umum",
    status: "hoax",
    date: "2026-01-24",
    source: "Kementerian Komunikasi dan Digital",
    sourceUrl: "https://www.komdigi.go.id/berita/berita-hoaks/detail/hoaks-listrik-padam-7-hari-dan-internet-mati-akibat-krisis-global",
    excerpt: "Narasi viral mengeklaim Indonesia akan mengalami pemadaman listrik total selama 7 hari disertai matinya internet akibat krisis global.",
    fullContent: "Faktanya, PT PLN (Persero) secara resmi membantah isu tersebut. Komdigi menegaskan hoaks ini berasal dari video Dharma Pongrekun yang dipotong di luar konteks — ia hanya membahas skenario darurat secara umum, bukan memberikan peringatan resmi pemadaman nasional. Sistem kelistrikan Indonesia dirancang dengan berlapis pengamanan dan PLN memiliki tim siaga 24 jam untuk setiap gangguan."
  },
  {
    id: 14,
    title: "[HOAKS] Rekrutmen Petugas Haji 2026 Mencatut Nama Kemenag RI",
    topic: "umum",
    status: "hoax",
    date: "2026-01-14",
    source: "TurnBackHoax (Mafindo)",
    sourceUrl: "https://turnbackhoax.id/articles/31632",
    excerpt: "Unggahan Facebook menawarkan posisi petugas haji 2026 menggunakan logo dan nama resmi Kementerian Agama, mengarahkan pendaftar ke situs eksternal.",
    fullContent: "Faktanya, pendaftaran petugas haji periode 1447 H/2026 M telah resmi ditutup sejak Desember 2025, dan peserta terpilih sudah memasuki tahap pelatihan sejak 10 Januari hingga 9 Februari 2026. Tautan pendaftaran palsu (gillyii.com) tidak memiliki afiliasi dengan portal resmi petugas.haji.go.id dan merupakan skema phishing yang berpotensi mencuri data pribadi."
  },
  {
    id: 15,
    title: "[HOAKS] Akun Facebook Wondr BNI Tawarkan Undian Berhadiah Maret 2026",
    topic: "ekonomi",
    status: "hoax",
    date: "2026-03-26",
    source: "Kompas Cek Fakta",
    sourceUrl: "https://www.kompas.com/cekfakta/read/2026/03/26/130241082/hoaks-akun-facebook-wondr-bni-tawarkan-undian-berhadiah-maret-2026",
    excerpt: "Sejumlah akun Facebook mengatasnamakan Wondr (aplikasi mobile banking BNI) menawarkan undian berhadiah berupa kendaraan, rumah, ponsel, dan paket umroh.",
    fullContent: "Faktanya, akun-akun tersebut adalah palsu. Akun Facebook resmi BNI menggunakan centang biru verifikasi, sementara undian Wondr hanya diselenggarakan melalui aplikasi resmi Wondr BNI — bukan melalui pendaftaran di media sosial. Direktur Consumer Banking BNI Corina Leyla Karnalies menegaskan: 'Itu hanya jebakan agar korban mentransfer sejumlah uang ke pelaku.' Masyarakat diminta tidak mengikuti arahan akun-akun tidak terverifikasi tersebut."
  },
  {
    id: 16,
    title: "[HOAKS] Dirjen Bimas Islam Kemenag Resmikan Dana Hibah Al-Bayti Saat Ramadhan",
    topic: "umum",
    status: "hoax",
    date: "2026-03-24",
    source: "Kompas Cek Fakta",
    sourceUrl: "https://www.kompas.com/cekfakta/read/2026/03/24/101000182/-hoaks-dirjen-bimas-islam-resmikan-dana-hibah-al-bayti-saat-ramadhan",
    excerpt: "Video mengeklaim Dirjen Bimas Islam Kemenag Abu Rokhmad meresmikan program dana hibah Al-Bayti dengan nominal Rp50 juta hingga Rp1 miliar, disertai nomor WhatsApp pendaftaran.",
    fullContent: "Faktanya, video tersebut adalah hasil manipulasi AI dengan tingkat deteksi akurasi 99,7 persen menggunakan tool Hive Moderation. Direktorat Jenderal Bimas Islam tidak pernah mengumumkan program serupa di media sosial resmi maupun website Kemenag. Dana hibah Al-Bayti merupakan skema penipuan yang telah beredar sebelumnya dan kini memakai wajah pejabat pemerintah hasil deepfake."
  },
  {
    id: 17,
    title: "[HOAKS] Program Sembako Gratis Ramadhan 1447 H dari Pertamina",
    topic: "ekonomi",
    status: "hoax",
    date: "2026-03-03",
    source: "Kompas Cek Fakta",
    sourceUrl: "https://www.kompas.com/cekfakta/read/2026/03/03/212100882/infografik--hoaks-program-sembako-ramadhan-dari-pertamina-cek-faktanya-",
    excerpt: "Unggahan media sosial mengeklaim PT Pertamina membagikan paket sembako gratis selama Ramadhan 1447 H di seluruh wilayah Indonesia.",
    fullContent: "Faktanya, Pertamina secara resmi membantah klaim tersebut. Tidak ada program pemberian sembako sebagaimana disampaikan dalam unggahan. Tautan yang disebarkan mengarah ke situs palsu yang dirancang untuk mencuri data pribadi pengguna. Masyarakat diimbau hanya mengakses informasi program resmi Pertamina melalui www.pertamina.com."
  },
  {
    id: 18,
    title: "[HOAKS] BMKG Prediksi Gempa Besar pada 5 Maret 2026",
    topic: "umum",
    status: "hoax",
    date: "2026-03-05",
    source: "Liputan6 Cek Fakta",
    sourceUrl: "https://www.liputan6.com/cek-fakta/read/6291489/cek-fakta-hoaks-bmkg-prediksi-gempa-besar-pada-5-maret-2026",
    excerpt: "Unggahan Facebook beredar mengklaim BMKG menghimbau seluruh rakyat Indonesia tentang kemungkinan terjadinya gempa besar skala besar pada 5 Maret 2026.",
    fullContent: "Faktanya, BMKG melalui akun Instagram resmi @infobmkg menegaskan: 'BMKG tidak pernah menyampaikan prediksi waktu pasti terjadinya gempa bumi. Hingga saat ini, ilmu pengetahuan dan teknologi belum mampu memprediksi kapan, di mana, dan seberapa besar gempa akan terjadi secara tepat dan akurat.' BMKG hanya melakukan pemantauan seismik rutin dan asesmen potensi bahaya, bukan prediksi tanggal gempa."
  },
  {
    id: 23,
    title: "[HOAKS] Video Prabowo Umumkan Bantuan Rp50 Juta untuk Seluruh Rakyat Indonesia",
    topic: "pejabat",
    status: "hoax",
    date: "2026-03-23",
    source: "Liputan6 Cek Fakta",
    sourceUrl: "https://www.liputan6.com/cek-fakta/read/6303105/deretan-hoaks-catut-nama-presiden-ri-dari-prabowo-hingga-sby",
    excerpt: "Video di Facebook memuat narasi Presiden Prabowo mengumumkan bantuan Rp50 juta untuk rakyat yang follow akun dan menekan tombol love.",
    fullContent: "Faktanya, video tersebut adalah manipulasi deepfake yang mencatut nama dan wajah Presiden Prabowo Subianto. Narasi 'silakan tekan tanda love dan panah, bantuan akan segera saya berikan' adalah modus penipuan engagement farming yang umum di media sosial. Tidak ada pengumuman bantuan resmi senilai Rp50 juta dari Presiden. Informasi resmi kepresidenan hanya tersedia di www.presidenri.go.id dan kanal resmi Sekretariat Presiden."
  },
  {
    id: 24,
    title: "[HOAKS] Foto Bus Pemudik Masuk Jurang Lebaran 2026",
    topic: "umum",
    status: "hoax",
    date: "2026-03-13",
    source: "Liputan6 Cek Fakta",
    sourceUrl: "https://www.liputan6.com/cek-fakta/read/6303463/cek-fakta-dalam-foto-ini-bukan-bus-pemudik-masuk-jurang",
    excerpt: "Foto bus terguling di lahan terbuka beredar di Facebook dengan klaim bus pemudik masuk jurang menjelang Lebaran 2026.",
    fullContent: "Faktanya, foto tersebut bukan kecelakaan bus pemudik Lebaran 2026. Hasil penelusuran menunjukkan foto itu adalah bus peziarah rombongan warga Serpong Utara, Tangerang Selatan, yang masuk jurang di Objek Wisata Pemandian Air Panas Guci, Tegal, Jawa Tengah — pada Minggu, 7 Mei 2023. Foto lama dari tiga tahun lalu ini disebarkan ulang seolah-olah sebagai insiden mudik terkini untuk memancing kepanikan."
  },
  {
    id: 25,
    title: "[HOAKS] Link Pendaftaran CPNS Polsuspas 2026 Dibuka di TikTok",
    topic: "kebijakan",
    status: "hoax",
    date: "2026-03-26",
    source: "Liputan6 Cek Fakta",
    sourceUrl: "https://www.liputan6.com/cek-fakta/read/6304445/cek-fakta-tidak-benar-link-pendaftaran-cpns-polsuspas-2026",
    excerpt: "Akun TikTok menyebarkan link pendaftaran CPNS Polisi Khusus Pemasyarakatan (Polsuspas) 2026 dengan klaim pendaftaran resmi dibuka.",
    fullContent: "Faktanya, Kementerian Imigrasi dan Pemasyarakatan melalui surat Sekretaris Jenderal tertanggal 9 Januari 2026 memastikan tidak ada pengumuman rekrutmen CPNS 2026. Badan Kepegawaian Negara (BKN) juga menegaskan pemerintah belum membuka seleksi CPNS tahun ini. Link yang beredar mengarah ke formulir tidak resmi yang mengumpulkan data pribadi. Rekrutmen CPNS resmi selalu diumumkan melalui sscasn.bkn.go.id."
  },
  {
    id: 26,
    title: "[HOAKS] Link Pendaftaran Bantuan Bibit Ayam Gratis dari Kementan 2026",
    topic: "umum",
    status: "hoax",
    date: "2026-03-03",
    source: "Liputan6 Cek Fakta",
    sourceUrl: "https://www.liputan6.com/cek-fakta/read/6289640/cek-fakta-hoaks-link-pendaftaran-bantuan-bibit-ayam-periode-21-februari-30-april-2026",
    excerpt: "Unggahan Facebook menawarkan program bantuan bibit ayam gratis dari pemerintah dengan kuota 5.000 nasional, termasuk DOC, pakan, imunisasi, dan modal usaha.",
    fullContent: "Faktanya, Direktorat Jenderal Peternakan dan Kesehatan Hewan (Ditjen PKH) Kementan mengeluarkan peringatan resmi: 'Hati-hati! Jangan mudah percaya akun mencurigakan atau link pendaftaran tidak resmi.' Link tersebut mengarahkan ke formulir yang meminta nomor KTP dan kontak Telegram — modus pencurian data pribadi. Informasi program bantuan ternak yang sah hanya tersedia di www.pertanian.go.id dan akun resmi Kementan."
  },
  {
    id: 27,
    title: "[HOAKS] Foto Wapres Gibran Bertemu Ayatollah Ali Khamenei Bahas Perlengkapan Tempur",
    topic: "pejabat",
    status: "hoax",
    date: "2026-03-31",
    source: "Kompas Cek Fakta",
    sourceUrl: "https://www.kompas.com/cekfakta/read/2026/03/31/175100182/infografik--muncul-hoaks-wapres-gibran-pernah-bertemu-ayatollah-ali",
    excerpt: "Foto memperlihatkan Wakil Presiden Gibran berdiskusi dengan Pemimpin Tertinggi Iran Ayatollah Ali Khamenei terkait pengiriman perlengkapan tempur ke Indonesia.",
    fullContent: "Faktanya, tidak ada pertemuan Gibran dengan pejabat Iran manapun, termasuk Ayatollah Ali Khamenei. Selama menjabat sebagai wakil presiden, Gibran tidak pernah berkunjung ke Iran. Analisis foto menggunakan Hive Moderation menunjukkan konten tersebut '99,9 persen merupakan AI generatif' — hasil manipulasi deepfake berbasis kecerdasan buatan yang dirancang untuk menciptakan narasi geopolitik palsu."
  },
  {
    id: 28,
    title: "[KLARIFIKASI] Tidak Benar Harga Pertamax Naik Jadi Rp17.850 per 1 April 2026",
    topic: "ekonomi",
    status: "hoax",
    date: "2026-03-31",
    source: "Kompas Cek Fakta",
    sourceUrl: "https://www.kompas.com/cekfakta/read/2026/03/31/111100882/-klarifikasi-tidak-benar-harga-pertamax-jadi-rp-17.850-pertamina-belum",
    excerpt: "Tabel proyeksi kenaikan harga BBM non-subsidi per April 2026 beredar di media sosial, mengeklaim Pertamax naik ke Rp17.850/liter dan Dexlite ke Rp23.650/liter.",
    fullContent: "Faktanya, Corporate Secretary Pertamina Roberth MV Dumatubun menyatakan: 'Tidak ada pengumuman resmi terkait harga per 1 April 2026.' Tabel yang beredar bukan berasal dari Pertamina. Informasi harga BBM yang valid hanya diumumkan melalui kanal resmi www.pertamina.com. Masyarakat diminta tidak menyebarkan tabel tidak resmi yang berpotensi memicu kepanikan."
  },
  {
    id: 29,
    title: "[HOAKS] Link Pendaftaran CPNS Kementerian Imigrasi 2026 Usia Maksimal 45 Tahun",
    topic: "kebijakan",
    status: "hoax",
    date: "2026-04-01",
    source: "Liputan6 Cek Fakta",
    sourceUrl: "https://www.liputan6.com/cek-fakta/read/6308280/cek-fakta-hoaks-link-pendaftaran-cpns-kementerian-imigrasi-2026-usia-maksimal-45-tahun",
    excerpt: "Unggahan Facebook menawarkan link pendaftaran CPNS Kementerian Imigrasi dan Pemasyarakatan 2026 dengan usia maksimal 45 tahun.",
    fullContent: "Faktanya, Kementerian Imigrasi dan Pemasyarakatan melalui pernyataan resmi 18 Februari 2026 menegaskan belum mengumumkan rekrutmen CPNS 2026. Seluruh informasi lowongan resmi hanya dipublikasikan melalui media dan website resmi kementerian. Pendaftaran CPNS yang sah hanya dilakukan melalui portal SSCASN di sscasn.bkn.go.id — bukan melalui link media sosial."
  },
  {
    id: 30,
    title: "[HOAKS] Bahlil Wajibkan Pengemudi Ojol Beli Motor Listrik Mulai 2026",
    topic: "kebijakan",
    status: "hoax",
    date: "2026-01-09",
    source: "TurnBackHoax (Mafindo)",
    sourceUrl: "https://turnbackhoax.id/articles/31564",
    excerpt: "Klaim beredar bahwa Menteri ESDM Bahlil Lahadalia mewajibkan pengemudi ojek online membeli motor listrik di tahun 2026 untuk mengurangi beban subsidi negara.",
    fullContent: "Faktanya, tidak ada pernyataan resmi dari Menteri Bahlil yang mendukung klaim tersebut. Bahlil sendiri menyatakan: 'Sampai sekarang tidak ada pembahasan dan tidak ada perubahan pola.' Kebijakan nasional yang berdampak pada jutaan orang pasti akan melalui pengumuman resmi, regulasi tertulis, dan pemberitaan media — tidak ada satupun yang bisa ditemukan untuk klaim ini."
  },
  {
    id: 31,
    title: "[HOAKS] Video Prabowo Umumkan THR Rp20 Triliun dari Hasil Rampasan Harta Koruptor",
    topic: "pejabat",
    status: "hoax",
    date: "2026-03-20",
    source: "ANTARA News",
    sourceUrl: "https://www.antaranews.com/berita/5479446/hoaks-video-prabowo-berikan-thr-total-rp20-triliun-untuk-masyarakat-yang-membutuhkan",
    excerpt: "Video di media sosial memperlihatkan Presiden Prabowo mengumumkan pemerintah akan membagikan THR total Rp20 triliun dari hasil rampasan harta koruptor kepada masyarakat yang membutuhkan.",
    fullContent: "Faktanya, video tersebut adalah hasil manipulasi AI. Hive Moderation mengidentifikasi suara Prabowo dalam video dihasilkan AI dengan probabilitas 99,9 persen, dikonfirmasi juga oleh Undetectable. Tidak ditemukan pernyataan resmi dari Presiden Prabowo terkait pembagian THR Rp20 triliun. Unggahan mengarahkan masyarakat ke nomor WhatsApp pribadi — modus penipuan yang sama dengan video deepfake Prabowo sebelumnya yang menjanjikan Rp40 juta dan Rp50 juta."
  },
  {
    id: 32,
    title: "[HOAKS] Gubernur Jawa Barat Dedi Mulyadi Adakan Program Tebus Motor Murah Rp500.000",
    topic: "pejabat",
    status: "hoax",
    date: "2026-03-12",
    source: "Kompas Cek Fakta",
    sourceUrl: "https://www.kompas.com/cekfakta/read/2026/03/02/181500582/-hoaks-dedi-mulyadi-adakan-tebus-motor-murah-rp-500.000",
    excerpt: "Video mengeklaim Gubernur Jawa Barat Dedi Mulyadi mengadakan program tebus motor murah seharga Rp500.000 untuk masyarakat.",
    fullContent: "Faktanya, video tersebut adalah rekayasa AI. Diskominfo Jawa Barat dan Jabar Saber Hoaks menegaskan tidak ada program tebus motor murah dari Gubernur Dedi Mulyadi. Verifikasi menggunakan TruthScan menunjukkan suara Dedi Mulyadi dalam video adalah AI generatif dengan probabilitas 99 persen. Tidak ada informasi terkait program tersebut di akun media sosial resmi Dedi Mulyadi maupun Pemprov Jabar."
  },
  {
    id: 33,
    title: "[HOAKS] Video Indonesia Kirimkan Bantuan Rudal untuk Iran",
    topic: "umum",
    status: "hoax",
    date: "2026-03-03",
    source: "TurnBackHoax (Mafindo)",
    sourceUrl: "https://turnbackhoax.id/articles/32852-parodi-indonesia-kirimkan-bantuan-rudal-untuk-iran",
    excerpt: "Video di Facebook memperlihatkan kumpulan benda panjang di atas truk tronton dengan narasi bahwa Indonesia mengirimkan bantuan rudal untuk Iran.",
    fullContent: "Faktanya, benda-benda yang terlihat di video bukanlah rudal melainkan tiang pancang (paku bumi) yang umum digunakan dalam proyek konstruksi infrastruktur. Konten ini diklasifikasikan sebagai parodi yang disalahartikan. Indonesia tidak pernah mengirimkan bantuan persenjataan ke Iran. Klaim serupa telah berulang kali beredar sejak 2025 dan selalu dibantah oleh Komdigi, Polri, serta Mafindo."
  },
  {
    id: 34,
    title: "[HOAKS] Informasi Seleksi CPNS Kemenkes 2026 Beredar di Media Sosial",
    topic: "kebijakan",
    status: "hoax",
    date: "2026-01-22",
    source: "Badan Kepegawaian Negara (BKN)",
    sourceUrl: "https://www.bkn.go.id/beredar-informasi-seleksi-kemenkes-2026-prof-zudan-itu-hoaks-rekrutmen-asn-terintegrasi-dan-diawasi-bkn/",
    excerpt: "Informasi tentang seleksi ASN Kementerian Kesehatan 2026 lengkap dengan daftar formasi, nominal gaji, dan link pendaftaran beredar luas di media sosial.",
    fullContent: "Faktanya, Kepala BKN Prof. Zudan menegaskan: 'Hingga saat ini belum ada pengumuman resmi terkait pembukaan seleksi ASN Tahun 2026.' Seluruh rekrutmen ASN — baik CPNS maupun PPPK — dijalankan melalui mekanisme nasional terintegrasi yang diawasi BKN, dan pendaftaran resmi hanya melalui portal SSCASN di sscasn.bkn.go.id. Link dan informasi formasi yang beredar di media sosial bukan berasal dari sumber resmi manapun."
  }
];
